### PR TITLE
revert ppsspp

### PR DESCRIPTION
**Pull request by raidenii**
reverted & stripped binary

### CODE REVIEW

**Comment by valadaa48** [comment]
there's a conflict

**Comment by valadaa48** [comment]
you can alternatively just get the old file and re-add the core in a new commit?

**Comment by raidenii** [comment]
that's what i did. but i had two commits on my fork ahead of yours (remember the pr rejected?), thus cannot merge your changes.

**Comment by raidenii** [comment]
let me try to rebase my repo to see if i can fix that

**Pull request closed without merging**
