### PR TITLE
hrydgard/ppsspp@52c6169

### PR DESCRIPTION
**Pull request by raidenii**
shanti's version seems missing commit info

### CODE REVIEW

**Comment by valadaa48** [comment]
I actually built ppsspp myself after we tried shanti's. If you're referring to my build, then do you know what might be missing from ppsspp-libretro in the rrvl repo?

**Comment by raidenii** [comment]
The core info is missing git commit version. I guess it's because distfile doesn't contain git metadata, which is what makefile relies on to get that commit info.

**Comment by valadaa48** [comment]
Is it an issue? The git commit is recorded in the package. Else we might be able to pass the git rev into the make process?

**Comment by raidenii** [comment]
Not really an issue, though it's harder to trace what version is currently running (especially from RA).

**Comment by valadaa48** [comment]
I just tried this core and I get a gpu exception when trying to load it.

**Comment by raidenii** [comment]
lol, it might be some of the optimization flags I used are too radical. Mind sharing your template?

**Comment by valadaa48** [comment]
I pushed it to the rrvl repo. Can you check ppsspp_libretro? You can also build the core from there, it should be pretty straight forward

**Comment by raidenii** [comment]
My template was based on that with some extra CFLAGS like O3 and math roundings. Maybe I should remove them and try again.Sent from phone2020年12月23日 下午10:30，valadaa48 <notifications@github.com>写道：
I pushed it to the rrvl repo. Can you check ppsspp_libretro? You can also build the core from there, it should be pretty straight forward

**Comment by raidenii** [comment]
Removed extra flags + at newer commit

**Comment by valadaa48** [comment]
Can you test this issue on your build? https://github.com/valadaa48/retroroller/issues/196

**Comment by raidenii** [comment]
I can reproduce the issue - the thing died at a 2nd launch. We should consider a rollback

**Comment by valadaa48** [comment]
Can you test the old version to see if it's there as well? It should be in git history here.

**Comment by raidenii** [comment]
Oh boy. Only the one in the first commit works. There's a good amount of bisecting needs to be done...

**Pull request closed without merging**
